name: Runs unit tests on project

on:
  push:
    branches:
      - '*'
    branches-ignore:
      - 'master'

jobs:
  ci-pr-head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        env:
          current_branch: ${GITHUB_REF#refs/heads/}
      - name: Change to pushed branch
        run: |
          git checkout $current_branch
      - name: Install packages
        run: |
          npm install
      - name: Run tests
        run: |
          npm test

  ci-pr-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        env:
          current_branch: ${GITHUB_REF#refs/heads/}
      - name: Merge branches
        run: |
          echo $current_branch
          git merge $current_branch
      - name: Install packages
        run: |
          npm install
      - name: Run tests
        run: |
          npm test
