name: Run tests on master branch

on:
  push:
    branches:
      - 'master'

jobs:
  ci-pr-head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Reset to last commmit made
        run: |
          git reset --hard HEAD
      - name: Install packages
        run: |
          npm install
      - name: Run tests
        run: |
          npm run unit && npm run functional
