name: setup project and run tests

on:
  push:
    branches:
      - '*'

jobs:
  ci-pr-head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        env:
          current_branch: ${GITHUB_REF#refs/heads/}
      - name: Install packages
        run: |
          git checkout $current_branch
          npm install
          npm test
