name: setup project and run tests

on: 
  push:
    branches:
      - '*'

jobs:
  setup-project-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        env:
          current_branch: ${GITHUB_REF#refs/heads/}
      - name: Install packages
        run: |
          git checkout $current_branch
          cd simple-battle-ships/
          npm install
          npm test
